# progress.ps1 - LAN-LOK decompilation progress tracker
# Run from the repo root: .\tools\progress.ps1

param(
    [switch]$Update   # If set, writes PROGRESS.md
)

$basFile  = Join-Path $PSScriptRoot "..\lanlokre.bas"
$planFile = Join-Path $PSScriptRoot "..\WORK_PLAN.md"

if (-not (Test-Path $basFile)) {
    Write-Error "Cannot find lanlokre.bas"
    exit 1
}

# --- Count lines ---
$allLines   = Get-Content $basFile
$totalLines = $allLines.Count
$asmLines   = ($allLines | Where-Object { $_ -match '^\s+01a2:[0-9a-f]{4}' }).Count
$basicLines = $totalLines - $asmLines

$pctDone    = [math]::Round(100.0 * $basicLines / $totalLines, 1)
$pctAsm     = [math]::Round(100.0 * $asmLines  / $totalLines, 1)

# Strings with percent sign (avoid % adjacent to $ in double-quoted strings)
$pctDoneStr = $pctDone.ToString() + "%"
$pctAsmStr  = $pctAsm.ToString()  + "%"

# --- Progress bar ---
$barWidth = 40
$filled   = [math]::Round($barWidth * $basicLines / $totalLines)
$bar      = ('#' * $filled) + ('-' * ($barWidth - $filled))

# --- Find first remaining ASM block ---
$firstAsm     = $allLines | Select-String -Pattern '^\s+01a2:[0-9a-f]{4}' | Select-Object -First 1
$firstAsmLine = if ($firstAsm) { $firstAsm.LineNumber } else { 0 }
$firstAsmAddr = if ($firstAsm) { [regex]::Match($firstAsm.Line, '01a2:([0-9a-f]{4})').Groups[1].Value } else { "N/A" }

# --- Function status from WORK_PLAN.md ---
$done = 0; $partial = 0; $todo = 0
if (Test-Path $planFile) {
    foreach ($line in (Get-Content $planFile)) {
        if ($line -match '\|\s+OK\s+\|'    -or $line -match '| OK |')  { $done++    }
        if ($line -match 'SS')                                           { }  # placeholder
        if ($line -match '\| Done \|')                                   { $done++    }
    }
    # More reliable: count emoji status markers
    $done    = 0; $partial = 0; $todo = 0
    $planContent = Get-Content $planFile -Raw
    $done    = ([regex]::Matches($planContent, 'Done')).Count
    $partial = ([regex]::Matches($planContent, 'Partial')).Count
    $todo    = ([regex]::Matches($planContent, 'Todo')).Count
}
$totalFns = $done + $partial + $todo

# --- Print report ---
Write-Host ""
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host " LAN-LOK Decompilation Progress" -ForegroundColor Cyan
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host (" Total lines:  " + $totalLines)
Write-Host ""

$asmColor = if ($asmLines -eq 0) { 'Green' } else { 'Yellow' }
Write-Host (" ASM remaining:  " + $asmLines + " lines (" + $pctAsmStr + ")") -ForegroundColor $asmColor
Write-Host (" BASIC done:     " + $basicLines + " lines (" + $pctDoneStr + ")") -ForegroundColor Green
Write-Host ""

$barColor = if ($pctDone -ge 100) { 'Green' } elseif ($pctDone -ge 50) { 'Yellow' } else { 'Red' }
Write-Host (" Progress: [" + $bar + "] " + $pctDoneStr) -ForegroundColor $barColor
Write-Host ""

if ($totalFns -gt 0) {
    Write-Host (" Functions: done=" + $done + "  partial=" + $partial + "  todo=" + $todo + "  (total=" + $totalFns + ")") -ForegroundColor Cyan
}
Write-Host ""

if ($firstAsmLine -gt 0) {
    Write-Host (" Next work:  lanlokre.bas line " + $firstAsmLine + "  (address 01a2:" + $firstAsmAddr + ")") -ForegroundColor Magenta
    Write-Host ("             Run: .\tools\extract_fn.ps1 -Address " + $firstAsmAddr) -ForegroundColor DarkGray
} else {
    Write-Host " ALL ASM DECOMPILED! Ready for renaming pass." -ForegroundColor Green
}

Write-Host ""
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host ""

# --- Optionally write PROGRESS.md ---
if ($Update) {
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
    $nextInfo  = if ($firstAsmLine -gt 0) { "line $firstAsmLine (01a2:$firstAsmAddr)" } else { "ALL DONE" }

    $lines = @(
        "# LAN-LOK Decompilation Progress",
        "",
        "*Auto-generated by tools/progress.ps1 on $timestamp*",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        "| Total lines in lanlokre.bas | $totalLines |",
        "| Raw ASM lines remaining | $asmLines ($pctAsmStr) |",
        "| BASIC lines done | $basicLines ($pctDoneStr) |",
        "| Functions done | $done |",
        "| Functions partial | $partial |",
        "| Functions todo | $todo |",
        "| Next ASM block | $nextInfo |",
        "",
        "## Progress Bar",
        "",
        "``[$bar] $pctDoneStr``",
        "",
        "See WORK_PLAN.md for the full function inventory and work protocol."
    )

    $progressFile = Join-Path $PSScriptRoot "..\PROGRESS.md"
    $lines | Out-File -FilePath $progressFile -Encoding utf8
    Write-Host "PROGRESS.md updated." -ForegroundColor Green
}
